services:
  # CÃ i Ä‘áº·t dá»‹ch vá»¥ bot chÃ­nh (Web Service)
  - type: web
    name: â‹†. ğ™šËšà¿” ğ’œğ“ˆğ“‰ğ“‡ğ’¶  ğœ—ğœšËšâ‹†
    env: python
    buildCommand: |
      apt-get update -y
      apt-get install -y ffmpeg  # Lá»‡nh cÃ i Ä‘áº·t FFmpeg
      pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_BOT_SECRET
        sync: false